// Generated by Scripts/generate_ui_icons.py. Edit Resources/UI/icons.json.
import CoreGraphics

nonisolated enum ProductIcon: String, CaseIterable, Sendable {
    case pen
    case line
    case arrow
    case rectangle
    case marker
    case text
    case blur
    case pixelate
    case step
    case undo
    case redo
    case print
    case copy
    case save
    case close
    case record
    case stop
    case capture
    case check
    case warning

    static let sourceHash = "6d2e85ff60e5481b8d8419533f2b3d6e2cb4297a623625a5adbf6dcfcc52ef94"
    static let size: CGFloat = 18

    // Generated exhaustive asset dispatch; no conditional application behavior.
    // swiftlint:disable:next cyclomatic_complexity
    func draw(in context: CGContext) {
        context.setLineCap(.round)
        context.setLineJoin(.round)
        context.setLineWidth(1.5)
        switch self {
        case .pen: drawPen(in: context)
        case .line: drawLine(in: context)
        case .arrow: drawArrow(in: context)
        case .rectangle: drawRectangle(in: context)
        case .marker: drawMarker(in: context)
        case .text: drawText(in: context)
        case .blur: drawBlur(in: context)
        case .pixelate: drawPixelate(in: context)
        case .step: drawStep(in: context)
        case .undo: drawUndo(in: context)
        case .redo: drawRedo(in: context)
        case .print: drawPrint(in: context)
        case .copy: drawCopy(in: context)
        case .save: drawSave(in: context)
        case .close: drawClose(in: context)
        case .record: drawRecord(in: context)
        case .stop: drawStop(in: context)
        case .capture: drawCapture(in: context)
        case .check: drawCheck(in: context)
        case .warning: drawWarning(in: context)
        }
    }
}

extension ProductIcon {

    nonisolated private func drawPen(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 9, y: 2))
        path0.addLine(to: CGPoint(x: 5, y: 8))
        path0.addLine(to: CGPoint(x: 5, y: 13))
        path0.addLine(to: CGPoint(x: 13, y: 13))
        path0.addLine(to: CGPoint(x: 13, y: 8))
        path0.closeSubpath()
        path0.move(to: CGPoint(x: 9, y: 2))
        path0.addLine(to: CGPoint(x: 9, y: 8))
        path0.move(to: CGPoint(x: 5, y: 10))
        path0.addLine(to: CGPoint(x: 13, y: 10))
        path0.move(to: CGPoint(x: 4.5, y: 16))
        path0.addLine(to: CGPoint(x: 13.5, y: 16))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawLine(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 3, y: 15))
        path0.addLine(to: CGPoint(x: 15, y: 3))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawArrow(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 3, y: 15))
        path0.addLine(to: CGPoint(x: 15, y: 3))
        path0.move(to: CGPoint(x: 7, y: 3))
        path0.addLine(to: CGPoint(x: 15, y: 3))
        path0.addLine(to: CGPoint(x: 15, y: 11))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawRectangle(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 4, y: 3.5))
        path0.addLine(to: CGPoint(x: 14, y: 3.5))
        path0.addCurve(to: CGPoint(x: 16, y: 5.5),
                         control1: CGPoint(x: 15.1, y: 3.5),
                         control2: CGPoint(x: 16, y: 4.4))
        path0.addLine(to: CGPoint(x: 16, y: 12.5))
        path0.addCurve(to: CGPoint(x: 14, y: 14.5),
                         control1: CGPoint(x: 16, y: 13.6),
                         control2: CGPoint(x: 15.1, y: 14.5))
        path0.addLine(to: CGPoint(x: 4, y: 14.5))
        path0.addCurve(to: CGPoint(x: 2, y: 12.5),
                         control1: CGPoint(x: 2.9, y: 14.5),
                         control2: CGPoint(x: 2, y: 13.6))
        path0.addLine(to: CGPoint(x: 2, y: 5.5))
        path0.addCurve(to: CGPoint(x: 4, y: 3.5),
                         control1: CGPoint(x: 2, y: 4.4),
                         control2: CGPoint(x: 2.9, y: 3.5))
        path0.closeSubpath()
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawMarker(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 4, y: 10.5))
        path0.addLine(to: CGPoint(x: 10.5, y: 4))
        path0.addLine(to: CGPoint(x: 14, y: 7.5))
        path0.addLine(to: CGPoint(x: 7.5, y: 14))
        path0.closeSubpath()
        path0.move(to: CGPoint(x: 10.5, y: 4))
        path0.addLine(to: CGPoint(x: 12.5, y: 2))
        path0.addLine(to: CGPoint(x: 16, y: 5.5))
        path0.addLine(to: CGPoint(x: 14, y: 7.5))
        path0.move(to: CGPoint(x: 4, y: 10.5))
        path0.addLine(to: CGPoint(x: 2.5, y: 14))
        path0.addLine(to: CGPoint(x: 5.5, y: 15.5))
        path0.addLine(to: CGPoint(x: 7.5, y: 14))
        path0.move(to: CGPoint(x: 2, y: 16))
        path0.addLine(to: CGPoint(x: 10, y: 16))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawText(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 2, y: 15))
        path0.addLine(to: CGPoint(x: 6, y: 3))
        path0.addLine(to: CGPoint(x: 10, y: 15))
        path0.move(to: CGPoint(x: 3.5, y: 10.5))
        path0.addLine(to: CGPoint(x: 8.5, y: 10.5))
        path0.move(to: CGPoint(x: 11.5, y: 9))
        path0.addCurve(to: CGPoint(x: 15.5, y: 10),
                         control1: CGPoint(x: 12.5, y: 7.5),
                         control2: CGPoint(x: 15.5, y: 7.5))
        path0.addLine(to: CGPoint(x: 15.5, y: 15))
        path0.move(to: CGPoint(x: 15.5, y: 11))
        path0.addLine(to: CGPoint(x: 12.5, y: 11))
        path0.addCurve(to: CGPoint(x: 12.5, y: 15),
                         control1: CGPoint(x: 10, y: 11),
                         control2: CGPoint(x: 10, y: 15))
        path0.addCurve(to: CGPoint(x: 15.5, y: 13),
                         control1: CGPoint(x: 14, y: 15),
                         control2: CGPoint(x: 15.5, y: 14))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawBlur(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 3, y: 4))
        path0.addCurve(to: CGPoint(x: 9, y: 4),
                         control1: CGPoint(x: 5, y: 2),
                         control2: CGPoint(x: 7, y: 6))
        path0.addCurve(to: CGPoint(x: 15, y: 4),
                         control1: CGPoint(x: 11, y: 2),
                         control2: CGPoint(x: 13, y: 6))
        path0.move(to: CGPoint(x: 3, y: 9))
        path0.addCurve(to: CGPoint(x: 9, y: 9),
                         control1: CGPoint(x: 5, y: 7),
                         control2: CGPoint(x: 7, y: 11))
        path0.addCurve(to: CGPoint(x: 15, y: 9),
                         control1: CGPoint(x: 11, y: 7),
                         control2: CGPoint(x: 13, y: 11))
        path0.move(to: CGPoint(x: 3, y: 14))
        path0.addCurve(to: CGPoint(x: 9, y: 14),
                         control1: CGPoint(x: 5, y: 12),
                         control2: CGPoint(x: 7, y: 16))
        path0.addCurve(to: CGPoint(x: 15, y: 14),
                         control1: CGPoint(x: 11, y: 12),
                         control2: CGPoint(x: 13, y: 16))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawPixelate(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 2.5, y: 2.5))
        path0.addLine(to: CGPoint(x: 7, y: 2.5))
        path0.addLine(to: CGPoint(x: 7, y: 7))
        path0.addLine(to: CGPoint(x: 2.5, y: 7))
        path0.closeSubpath()
        path0.move(to: CGPoint(x: 10.5, y: 10.5))
        path0.addLine(to: CGPoint(x: 15, y: 10.5))
        path0.addLine(to: CGPoint(x: 15, y: 15))
        path0.addLine(to: CGPoint(x: 10.5, y: 15))
        path0.closeSubpath()
        context.addPath(path0)
        context.drawPath(using: .fill)
        let path1 = CGMutablePath()
        path1.move(to: CGPoint(x: 10.5, y: 2.5))
        path1.addLine(to: CGPoint(x: 15, y: 2.5))
        path1.addLine(to: CGPoint(x: 15, y: 7))
        path1.addLine(to: CGPoint(x: 10.5, y: 7))
        path1.closeSubpath()
        path1.move(to: CGPoint(x: 2.5, y: 10.5))
        path1.addLine(to: CGPoint(x: 7, y: 10.5))
        path1.addLine(to: CGPoint(x: 7, y: 15))
        path1.addLine(to: CGPoint(x: 2.5, y: 15))
        path1.closeSubpath()
        context.addPath(path1)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawStep(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 16, y: 9))
        path0.addCurve(to: CGPoint(x: 9, y: 16),
                         control1: CGPoint(x: 16, y: 12.866),
                         control2: CGPoint(x: 12.866, y: 16))
        path0.addCurve(to: CGPoint(x: 2, y: 9),
                         control1: CGPoint(x: 5.134, y: 16),
                         control2: CGPoint(x: 2, y: 12.866))
        path0.addCurve(to: CGPoint(x: 9, y: 2),
                         control1: CGPoint(x: 2, y: 5.134),
                         control2: CGPoint(x: 5.134, y: 2))
        path0.addCurve(to: CGPoint(x: 16, y: 9),
                         control1: CGPoint(x: 12.866, y: 2),
                         control2: CGPoint(x: 16, y: 5.134))
        path0.closeSubpath()
        context.addPath(path0)
        context.drawPath(using: .stroke)
        let path1 = CGMutablePath()
        path1.move(to: CGPoint(x: 7, y: 7))
        path1.addLine(to: CGPoint(x: 9, y: 5.5))
        path1.addLine(to: CGPoint(x: 9, y: 12.5))
        path1.move(to: CGPoint(x: 7, y: 12.5))
        path1.addLine(to: CGPoint(x: 11, y: 12.5))
        context.addPath(path1)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawUndo(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 6, y: 3))
        path0.addLine(to: CGPoint(x: 2, y: 7))
        path0.addLine(to: CGPoint(x: 6, y: 11))
        path0.move(to: CGPoint(x: 2, y: 7))
        path0.addLine(to: CGPoint(x: 10.5, y: 7))
        path0.addCurve(to: CGPoint(x: 10.5, y: 15),
                         control1: CGPoint(x: 17, y: 7),
                         control2: CGPoint(x: 17, y: 15))
        path0.addLine(to: CGPoint(x: 8, y: 15))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawRedo(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 12, y: 3))
        path0.addLine(to: CGPoint(x: 16, y: 7))
        path0.addLine(to: CGPoint(x: 12, y: 11))
        path0.move(to: CGPoint(x: 16, y: 7))
        path0.addLine(to: CGPoint(x: 7.5, y: 7))
        path0.addCurve(to: CGPoint(x: 7.5, y: 15),
                         control1: CGPoint(x: 1, y: 7),
                         control2: CGPoint(x: 1, y: 15))
        path0.addLine(to: CGPoint(x: 10, y: 15))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawPrint(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 5, y: 6))
        path0.addLine(to: CGPoint(x: 5, y: 2))
        path0.addLine(to: CGPoint(x: 13, y: 2))
        path0.addLine(to: CGPoint(x: 13, y: 6))
        path0.move(to: CGPoint(x: 5, y: 13))
        path0.addLine(to: CGPoint(x: 2, y: 13))
        path0.addLine(to: CGPoint(x: 2, y: 7))
        path0.addCurve(to: CGPoint(x: 3, y: 6),
                         control1: CGPoint(x: 2, y: 6.4),
                         control2: CGPoint(x: 2.4, y: 6))
        path0.addLine(to: CGPoint(x: 15, y: 6))
        path0.addCurve(to: CGPoint(x: 16, y: 7),
                         control1: CGPoint(x: 15.6, y: 6),
                         control2: CGPoint(x: 16, y: 6.4))
        path0.addLine(to: CGPoint(x: 16, y: 13))
        path0.addLine(to: CGPoint(x: 13, y: 13))
        path0.move(to: CGPoint(x: 5, y: 10))
        path0.addLine(to: CGPoint(x: 13, y: 10))
        path0.addLine(to: CGPoint(x: 13, y: 16))
        path0.addLine(to: CGPoint(x: 5, y: 16))
        path0.closeSubpath()
        path0.move(to: CGPoint(x: 13.5, y: 8))
        path0.addLine(to: CGPoint(x: 14, y: 8))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawCopy(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 7, y: 6))
        path0.addLine(to: CGPoint(x: 14, y: 6))
        path0.addCurve(to: CGPoint(x: 15, y: 7),
                         control1: CGPoint(x: 14.6, y: 6),
                         control2: CGPoint(x: 15, y: 6.4))
        path0.addLine(to: CGPoint(x: 15, y: 15))
        path0.addCurve(to: CGPoint(x: 14, y: 16),
                         control1: CGPoint(x: 15, y: 15.6),
                         control2: CGPoint(x: 14.6, y: 16))
        path0.addLine(to: CGPoint(x: 7, y: 16))
        path0.addCurve(to: CGPoint(x: 6, y: 15),
                         control1: CGPoint(x: 6.4, y: 16),
                         control2: CGPoint(x: 6, y: 15.6))
        path0.addLine(to: CGPoint(x: 6, y: 7))
        path0.addCurve(to: CGPoint(x: 7, y: 6),
                         control1: CGPoint(x: 6, y: 6.4),
                         control2: CGPoint(x: 6.4, y: 6))
        path0.closeSubpath()
        path0.move(to: CGPoint(x: 4, y: 12))
        path0.addLine(to: CGPoint(x: 3, y: 12))
        path0.addCurve(to: CGPoint(x: 2, y: 11),
                         control1: CGPoint(x: 2.4, y: 12),
                         control2: CGPoint(x: 2, y: 11.6))
        path0.addLine(to: CGPoint(x: 2, y: 3))
        path0.addCurve(to: CGPoint(x: 3, y: 2),
                         control1: CGPoint(x: 2, y: 2.4),
                         control2: CGPoint(x: 2.4, y: 2))
        path0.addLine(to: CGPoint(x: 10, y: 2))
        path0.addCurve(to: CGPoint(x: 11, y: 3),
                         control1: CGPoint(x: 10.6, y: 2),
                         control2: CGPoint(x: 11, y: 2.4))
        path0.addLine(to: CGPoint(x: 11, y: 4))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawSave(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 9, y: 2))
        path0.addLine(to: CGPoint(x: 9, y: 11))
        path0.move(to: CGPoint(x: 5.5, y: 7.5))
        path0.addLine(to: CGPoint(x: 9, y: 11))
        path0.addLine(to: CGPoint(x: 12.5, y: 7.5))
        path0.move(to: CGPoint(x: 5, y: 5))
        path0.addLine(to: CGPoint(x: 3, y: 5))
        path0.addCurve(to: CGPoint(x: 2, y: 6),
                         control1: CGPoint(x: 2.4, y: 5),
                         control2: CGPoint(x: 2, y: 5.4))
        path0.addLine(to: CGPoint(x: 2, y: 15))
        path0.addCurve(to: CGPoint(x: 3, y: 16),
                         control1: CGPoint(x: 2, y: 15.6),
                         control2: CGPoint(x: 2.4, y: 16))
        path0.addLine(to: CGPoint(x: 15, y: 16))
        path0.addCurve(to: CGPoint(x: 16, y: 15),
                         control1: CGPoint(x: 15.6, y: 16),
                         control2: CGPoint(x: 16, y: 15.6))
        path0.addLine(to: CGPoint(x: 16, y: 6))
        path0.addCurve(to: CGPoint(x: 15, y: 5),
                         control1: CGPoint(x: 16, y: 5.4),
                         control2: CGPoint(x: 15.6, y: 5))
        path0.addLine(to: CGPoint(x: 13, y: 5))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawClose(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 4, y: 4))
        path0.addLine(to: CGPoint(x: 14, y: 14))
        path0.move(to: CGPoint(x: 14, y: 4))
        path0.addLine(to: CGPoint(x: 4, y: 14))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawRecord(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 16, y: 9))
        path0.addCurve(to: CGPoint(x: 9, y: 16),
                         control1: CGPoint(x: 16, y: 12.866),
                         control2: CGPoint(x: 12.866, y: 16))
        path0.addCurve(to: CGPoint(x: 2, y: 9),
                         control1: CGPoint(x: 5.134, y: 16),
                         control2: CGPoint(x: 2, y: 12.866))
        path0.addCurve(to: CGPoint(x: 9, y: 2),
                         control1: CGPoint(x: 2, y: 5.134),
                         control2: CGPoint(x: 5.134, y: 2))
        path0.addCurve(to: CGPoint(x: 16, y: 9),
                         control1: CGPoint(x: 12.866, y: 2),
                         control2: CGPoint(x: 16, y: 5.134))
        path0.closeSubpath()
        context.addPath(path0)
        context.drawPath(using: .stroke)
        let path1 = CGMutablePath()
        path1.move(to: CGPoint(x: 12, y: 9))
        path1.addCurve(to: CGPoint(x: 9, y: 12),
                         control1: CGPoint(x: 12, y: 10.657),
                         control2: CGPoint(x: 10.657, y: 12))
        path1.addCurve(to: CGPoint(x: 6, y: 9),
                         control1: CGPoint(x: 7.343, y: 12),
                         control2: CGPoint(x: 6, y: 10.657))
        path1.addCurve(to: CGPoint(x: 9, y: 6),
                         control1: CGPoint(x: 6, y: 7.343),
                         control2: CGPoint(x: 7.343, y: 6))
        path1.addCurve(to: CGPoint(x: 12, y: 9),
                         control1: CGPoint(x: 10.657, y: 6),
                         control2: CGPoint(x: 12, y: 7.343))
        path1.closeSubpath()
        context.addPath(path1)
        context.drawPath(using: .fill)
    }

    nonisolated private func drawStop(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 4.5, y: 3.5))
        path0.addLine(to: CGPoint(x: 13.5, y: 3.5))
        path0.addCurve(to: CGPoint(x: 14.5, y: 4.5),
                         control1: CGPoint(x: 14.052, y: 3.5),
                         control2: CGPoint(x: 14.5, y: 3.948))
        path0.addLine(to: CGPoint(x: 14.5, y: 13.5))
        path0.addCurve(to: CGPoint(x: 13.5, y: 14.5),
                         control1: CGPoint(x: 14.5, y: 14.052),
                         control2: CGPoint(x: 14.052, y: 14.5))
        path0.addLine(to: CGPoint(x: 4.5, y: 14.5))
        path0.addCurve(to: CGPoint(x: 3.5, y: 13.5),
                         control1: CGPoint(x: 3.948, y: 14.5),
                         control2: CGPoint(x: 3.5, y: 14.052))
        path0.addLine(to: CGPoint(x: 3.5, y: 4.5))
        path0.addCurve(to: CGPoint(x: 4.5, y: 3.5),
                         control1: CGPoint(x: 3.5, y: 3.948),
                         control2: CGPoint(x: 3.948, y: 3.5))
        path0.closeSubpath()
        context.addPath(path0)
        context.drawPath(using: .fill)
    }

    nonisolated private func drawCapture(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 2, y: 6))
        path0.addLine(to: CGPoint(x: 2, y: 3))
        path0.addCurve(to: CGPoint(x: 3, y: 2),
                         control1: CGPoint(x: 2, y: 2.4),
                         control2: CGPoint(x: 2.4, y: 2))
        path0.addLine(to: CGPoint(x: 6, y: 2))
        path0.move(to: CGPoint(x: 12, y: 2))
        path0.addLine(to: CGPoint(x: 15, y: 2))
        path0.addCurve(to: CGPoint(x: 16, y: 3),
                         control1: CGPoint(x: 15.6, y: 2),
                         control2: CGPoint(x: 16, y: 2.4))
        path0.addLine(to: CGPoint(x: 16, y: 6))
        path0.move(to: CGPoint(x: 16, y: 12))
        path0.addLine(to: CGPoint(x: 16, y: 15))
        path0.addCurve(to: CGPoint(x: 15, y: 16),
                         control1: CGPoint(x: 16, y: 15.6),
                         control2: CGPoint(x: 15.6, y: 16))
        path0.addLine(to: CGPoint(x: 12, y: 16))
        path0.move(to: CGPoint(x: 6, y: 16))
        path0.addLine(to: CGPoint(x: 3, y: 16))
        path0.addCurve(to: CGPoint(x: 2, y: 15),
                         control1: CGPoint(x: 2.4, y: 16),
                         control2: CGPoint(x: 2, y: 15.6))
        path0.addLine(to: CGPoint(x: 2, y: 12))
        path0.move(to: CGPoint(x: 6, y: 12))
        path0.addLine(to: CGPoint(x: 12, y: 6))
        path0.move(to: CGPoint(x: 8, y: 6))
        path0.addLine(to: CGPoint(x: 12, y: 6))
        path0.addLine(to: CGPoint(x: 12, y: 10))
        context.addPath(path0)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawCheck(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 16, y: 9))
        path0.addCurve(to: CGPoint(x: 9, y: 16),
                         control1: CGPoint(x: 16, y: 12.866),
                         control2: CGPoint(x: 12.866, y: 16))
        path0.addCurve(to: CGPoint(x: 2, y: 9),
                         control1: CGPoint(x: 5.134, y: 16),
                         control2: CGPoint(x: 2, y: 12.866))
        path0.addCurve(to: CGPoint(x: 9, y: 2),
                         control1: CGPoint(x: 2, y: 5.134),
                         control2: CGPoint(x: 5.134, y: 2))
        path0.addCurve(to: CGPoint(x: 16, y: 9),
                         control1: CGPoint(x: 12.866, y: 2),
                         control2: CGPoint(x: 16, y: 5.134))
        path0.closeSubpath()
        context.addPath(path0)
        context.drawPath(using: .stroke)
        let path1 = CGMutablePath()
        path1.move(to: CGPoint(x: 5.5, y: 9))
        path1.addLine(to: CGPoint(x: 8, y: 11.5))
        path1.addLine(to: CGPoint(x: 12.5, y: 6.5))
        context.addPath(path1)
        context.drawPath(using: .stroke)
    }

    nonisolated private func drawWarning(in context: CGContext) {
        let path0 = CGMutablePath()
        path0.move(to: CGPoint(x: 9, y: 2))
        path0.addLine(to: CGPoint(x: 16, y: 15.5))
        path0.addLine(to: CGPoint(x: 2, y: 15.5))
        path0.closeSubpath()
        path0.move(to: CGPoint(x: 9, y: 6))
        path0.addLine(to: CGPoint(x: 9, y: 10.5))
        context.addPath(path0)
        context.drawPath(using: .stroke)
        let path1 = CGMutablePath()
        path1.move(to: CGPoint(x: 9.75, y: 13))
        path1.addCurve(to: CGPoint(x: 9, y: 13.75),
                         control1: CGPoint(x: 9.75, y: 13.414),
                         control2: CGPoint(x: 9.414, y: 13.75))
        path1.addCurve(to: CGPoint(x: 8.25, y: 13),
                         control1: CGPoint(x: 8.586, y: 13.75),
                         control2: CGPoint(x: 8.25, y: 13.414))
        path1.addCurve(to: CGPoint(x: 9, y: 12.25),
                         control1: CGPoint(x: 8.25, y: 12.586),
                         control2: CGPoint(x: 8.586, y: 12.25))
        path1.addCurve(to: CGPoint(x: 9.75, y: 13),
                         control1: CGPoint(x: 9.414, y: 12.25),
                         control2: CGPoint(x: 9.75, y: 12.586))
        path1.closeSubpath()
        context.addPath(path1)
        context.drawPath(using: .fill)
    }
}
