#!/usr/bin/env python3
"""Compile the original shared vector catalogue to dependency-free native paths."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Resources/UI/icons.json"
ARITY = {"M": 2, "L": 2, "C": 6, "Z": 0}


def commands(path):
    tokens = re.findall(r"[MLCZ]|-?\d+(?:\.\d+)?", path)
    if "".join(tokens) != re.sub(r"[\s,]", "", path):
        raise ValueError("Only absolute M/L/C/Z paths are supported")
    index = 0
    while index < len(tokens):
        command = tokens[index]
        count = ARITY[command]
        values = tokens[index + 1:index + 1 + count]
        if len(values) != count or any(value in ARITY for value in values):
            raise ValueError("Incomplete path command")
        yield command, values
        index += count + 1


def catalogue():
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    size, stroke = data["size"], data["strokeWidth"]
    assert size > 0 and stroke > 0
    assert data["icons"]
    for name, layers in data["icons"].items():
        assert re.fullmatch(r"[a-z]+", name) and layers
        for layer in layers:
            assert layer.get("fill", False) or layer.get("stroke", True)
            parsed = list(commands(layer["path"]))
            assert parsed[0][0] == "M"
            for _, values in parsed:
                assert all(0 <= float(value) <= size for value in values)
    return data, hashlib.sha256(raw).hexdigest()


def swift(data, digest):
    lines = ["// Generated by Scripts/generate_ui_icons.py. Edit Resources/UI/icons.json.",
             "import CoreGraphics", "", "nonisolated enum ProductIcon: String, CaseIterable, Sendable {"]
    lines += [f"    case {name}" for name in data["icons"]]
    lines += ["", f'    static let sourceHash = "{digest}"',
              f'    static let size: CGFloat = {data["size"]}', "",
              "    // Generated exhaustive asset dispatch; no conditional application behavior.",
              "    // swiftlint:disable:next cyclomatic_complexity",
              "    func draw(in context: CGContext) {", "        context.setLineCap(.round)",
              "        context.setLineJoin(.round)", f'        context.setLineWidth({data["strokeWidth"]})',
              "        switch self {"]
    lines += [f"        case .{name}: draw{name.title()}(in: context)" for name in data["icons"]]
    lines += ["        }", "    }", "}", "", "extension ProductIcon {"]
    for name, layers in data["icons"].items():
        lines += ["", f"    nonisolated private func draw{name.title()}(in context: CGContext) {{"]
        for index, layer in enumerate(layers):
            path = f"path{index}"
            lines.append(f"        let {path} = CGMutablePath()")
            for command, values in commands(layer["path"]):
                if command == "M": action = f"move(to: CGPoint(x: {values[0]}, y: {values[1]}))"
                elif command == "L": action = f"addLine(to: CGPoint(x: {values[0]}, y: {values[1]}))"
                elif command == "C":
                    lines += [f"        {path}.addCurve(to: CGPoint(x: {values[4]}, y: {values[5]}),",
                              f"                         control1: CGPoint(x: {values[0]}, y: {values[1]}),",
                              f"                         control2: CGPoint(x: {values[2]}, y: {values[3]}))"]
                    continue
                else: action = "closeSubpath()"
                lines.append(f"        {path}.{action}")
            mode = "fillStroke" if layer.get("fill", False) and layer.get("stroke", True) else "fill" if layer.get("fill", False) else "stroke"
            lines += [f"        context.addPath({path})", f"        context.drawPath(using: .{mode})"]
        lines.append("    }")
    return "\n".join(lines + ["}", ""])


def csharp(data, digest):
    lines = ["// Generated by Scripts/generate_ui_icons.py. Edit Resources/UI/icons.json.",
             "using System.Windows.Media;", "", "namespace Slightshot;", "",
             "internal enum ProductIcon { " + ", ".join(name.title() for name in data["icons"]) + " }", "",
             "internal static class ProductIcons", "{", f'    internal const string SourceHash = "{digest}";',
             f'    internal const double Size = {data["size"]};',
             "    private sealed record Layer(Geometry Path, bool Fill, bool Stroke);",
             "    private static Layer Shape(string path, bool fill, bool stroke)",
             "    {", "        Geometry geometry = Geometry.Parse(path); geometry.Freeze();",
             "        return new(geometry, fill, stroke);", "    }",
             "    private static readonly Dictionary<ProductIcon, Layer[]> Layers = new()", "    {"]
    for name, layers in data["icons"].items():
        lines.append(f"        [ProductIcon.{name.title()}] = [")
        for layer in layers:
            fill = str(layer.get("fill", False)).lower()
            stroke = str(layer.get("stroke", True)).lower()
            lines.append(f'            Shape("{layer["path"]}", {fill}, {stroke}),')
        lines.append("        ],")
    lines += ["    };", "", "    internal static void Draw(ProductIcon icon, DrawingContext context, Brush brush)",
              "    {", f'        var pen = new Pen(brush, {data["strokeWidth"]}) {{ StartLineCap = PenLineCap.Round, EndLineCap = PenLineCap.Round, LineJoin = PenLineJoin.Round }};',
              "        foreach (Layer layer in Layers[icon])", "        context.DrawGeometry(layer.Fill ? brush : null, layer.Stroke ? pen : null, layer.Path);", "    }", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed native paths differ from the catalogue")
    args = parser.parse_args()
    data, digest = catalogue()
    outputs = {ROOT / "Sources/Slightshot/Overlay/ProductIcon.generated.swift": swift(data, digest),
               ROOT / "Windows/Slightshot/ProductIcons.generated.cs": csharp(data, digest)}
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content: stale.append(str(path.relative_to(ROOT)))
        else: path.write_text(content)
    if stale:
        print("Regenerate shared icons: python3 Scripts/generate_ui_icons.py\n" + "\n".join(stale), file=sys.stderr)
        return 1
    print(f"{len(data['icons'])} original shared icons; native paths {'verified' if args.check else 'generated'} ({digest[:12]}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
