// Generated by Scripts/generate_ui_icons.py. Edit Resources/UI/icons.json.
using System.Windows.Media;

namespace Slightshot;

internal enum ProductIcon { Pen, Line, Arrow, Rectangle, Marker, Text, Blur, Pixelate, Undo, Print, Copy, Save, Close, Record, Stop, Capture, Check, Warning }

internal static class ProductIcons
{
    internal const string SourceHash = "d934be9a9a96579ebf61c63647eda91196beddf0c818b5ba11cfe631085a518b";
    internal const double Size = 18;
    private sealed record Layer(Geometry Path, bool Fill, bool Stroke);
    private static Layer Shape(string path, bool fill, bool stroke)
    {
        Geometry geometry = Geometry.Parse(path); geometry.Freeze();
        return new(geometry, fill, stroke);
    }
    private static readonly Dictionary<ProductIcon, Layer[]> Layers = new()
    {
        [ProductIcon.Pen] = [
            Shape("M9 2 L5 8 L5 13 L13 13 L13 8 Z M9 2 L9 8 M5 10 L13 10 M4.5 16 L13.5 16", false, true),
        ],
        [ProductIcon.Line] = [
            Shape("M3 15 L15 3", false, true),
        ],
        [ProductIcon.Arrow] = [
            Shape("M3 15 L15 3 M7 3 L15 3 L15 11", false, true),
        ],
        [ProductIcon.Rectangle] = [
            Shape("M4 3.5 L14 3.5 C15.1 3.5 16 4.4 16 5.5 L16 12.5 C16 13.6 15.1 14.5 14 14.5 L4 14.5 C2.9 14.5 2 13.6 2 12.5 L2 5.5 C2 4.4 2.9 3.5 4 3.5 Z", false, true),
        ],
        [ProductIcon.Marker] = [
            Shape("M4 10.5 L10.5 4 L14 7.5 L7.5 14 Z M10.5 4 L12.5 2 L16 5.5 L14 7.5 M4 10.5 L2.5 14 L5.5 15.5 L7.5 14 M2 16 L10 16", false, true),
        ],
        [ProductIcon.Text] = [
            Shape("M2 15 L6 3 L10 15 M3.5 10.5 L8.5 10.5 M11.5 9 C12.5 7.5 15.5 7.5 15.5 10 L15.5 15 M15.5 11 L12.5 11 C10 11 10 15 12.5 15 C14 15 15.5 14 15.5 13", false, true),
        ],
        [ProductIcon.Blur] = [
            Shape("M3 4 C5 2 7 6 9 4 C11 2 13 6 15 4 M3 9 C5 7 7 11 9 9 C11 7 13 11 15 9 M3 14 C5 12 7 16 9 14 C11 12 13 16 15 14", false, true),
        ],
        [ProductIcon.Pixelate] = [
            Shape("M2.5 2.5 L7 2.5 L7 7 L2.5 7 Z M10.5 10.5 L15 10.5 L15 15 L10.5 15 Z", true, false),
            Shape("M10.5 2.5 L15 2.5 L15 7 L10.5 7 Z M2.5 10.5 L7 10.5 L7 15 L2.5 15 Z", false, true),
        ],
        [ProductIcon.Undo] = [
            Shape("M6 3 L2 7 L6 11 M2 7 L10.5 7 C17 7 17 15 10.5 15 L8 15", false, true),
        ],
        [ProductIcon.Print] = [
            Shape("M5 6 L5 2 L13 2 L13 6 M5 13 L2 13 L2 7 C2 6.4 2.4 6 3 6 L15 6 C15.6 6 16 6.4 16 7 L16 13 L13 13 M5 10 L13 10 L13 16 L5 16 Z M13.5 8 L14 8", false, true),
        ],
        [ProductIcon.Copy] = [
            Shape("M7 6 L14 6 C14.6 6 15 6.4 15 7 L15 15 C15 15.6 14.6 16 14 16 L7 16 C6.4 16 6 15.6 6 15 L6 7 C6 6.4 6.4 6 7 6 Z M4 12 L3 12 C2.4 12 2 11.6 2 11 L2 3 C2 2.4 2.4 2 3 2 L10 2 C10.6 2 11 2.4 11 3 L11 4", false, true),
        ],
        [ProductIcon.Save] = [
            Shape("M9 2 L9 11 M5.5 7.5 L9 11 L12.5 7.5 M5 5 L3 5 C2.4 5 2 5.4 2 6 L2 15 C2 15.6 2.4 16 3 16 L15 16 C15.6 16 16 15.6 16 15 L16 6 C16 5.4 15.6 5 15 5 L13 5", false, true),
        ],
        [ProductIcon.Close] = [
            Shape("M4 4 L14 14 M14 4 L4 14", false, true),
        ],
        [ProductIcon.Record] = [
            Shape("M16 9 C16 12.866 12.866 16 9 16 C5.134 16 2 12.866 2 9 C2 5.134 5.134 2 9 2 C12.866 2 16 5.134 16 9 Z", false, true),
            Shape("M12 9 C12 10.657 10.657 12 9 12 C7.343 12 6 10.657 6 9 C6 7.343 7.343 6 9 6 C10.657 6 12 7.343 12 9 Z", true, false),
        ],
        [ProductIcon.Stop] = [
            Shape("M4.5 3.5 L13.5 3.5 C14.052 3.5 14.5 3.948 14.5 4.5 L14.5 13.5 C14.5 14.052 14.052 14.5 13.5 14.5 L4.5 14.5 C3.948 14.5 3.5 14.052 3.5 13.5 L3.5 4.5 C3.5 3.948 3.948 3.5 4.5 3.5 Z", true, false),
        ],
        [ProductIcon.Capture] = [
            Shape("M2 6 L2 3 C2 2.4 2.4 2 3 2 L6 2 M12 2 L15 2 C15.6 2 16 2.4 16 3 L16 6 M16 12 L16 15 C16 15.6 15.6 16 15 16 L12 16 M6 16 L3 16 C2.4 16 2 15.6 2 15 L2 12 M6 12 L12 6 M8 6 L12 6 L12 10", false, true),
        ],
        [ProductIcon.Check] = [
            Shape("M16 9 C16 12.866 12.866 16 9 16 C5.134 16 2 12.866 2 9 C2 5.134 5.134 2 9 2 C12.866 2 16 5.134 16 9 Z", false, true),
            Shape("M5.5 9 L8 11.5 L12.5 6.5", false, true),
        ],
        [ProductIcon.Warning] = [
            Shape("M9 2 L16 15.5 L2 15.5 Z M9 6 L9 10.5", false, true),
            Shape("M9.75 13 C9.75 13.414 9.414 13.75 9 13.75 C8.586 13.75 8.25 13.414 8.25 13 C8.25 12.586 8.586 12.25 9 12.25 C9.414 12.25 9.75 12.586 9.75 13 Z", true, false),
        ],
    };

    internal static void Draw(ProductIcon icon, DrawingContext context, Brush brush)
    {
        var pen = new Pen(brush, 1.5) { StartLineCap = PenLineCap.Round, EndLineCap = PenLineCap.Round, LineJoin = PenLineJoin.Round };
        foreach (Layer layer in Layers[icon])
        context.DrawGeometry(layer.Fill ? brush : null, layer.Stroke ? pen : null, layer.Path);
    }
}
